use std::collections::{HashMap,HashSet};
#[derive(Debug,Clone)]pub enum N{L{i:String,v:V},R{i:String,t:String},O{i:String,o:O,a:Vec<A>},S{i:String,n:Vec<N>},F{i:String,p:Vec<String>,b:Vec<N>},W{s:A,d:D},B(String)}
#[derive(Debug,Clone)]pub enum V{I(i64),F(f64),S(String),P(Box<V>,Box<V>)}
#[derive(Debug,Clone)]pub enum A{R(String),L(V),E(O,Vec<A>)}
#[derive(Debug,Clone,PartialEq,Eq,Hash)]pub enum O{Add,Sub,Mul,Div,Mod,Neg,Eq,Ne,Lt,Gt,Le,Ge,And,Or,Not,Seq,Map,Fld,Flt,Len,Fst,Snd,Brn,Prt,Inp,Opn,Acc,Get,Put,Cls,Err,Tcp,Udp,Bnd,Lst,Con,Xmt,Rcv,Sel,Rdy,Nbk,Ndl,Qck,Sbf,Kal,Epl,Ewa,Ect,Thr,Jon,Mtx,Lck,Ulk,Que,Psh,Pop,Ret,Alc,Fre,Chk,Win,Shw,Hid,Evt,Run,Lbl,Txb,Btn,Dlg,Gvl,Svl,Cal(String)}
#[derive(Debug,Clone)]pub enum D{N(String),C(String),E(E)}
#[derive(Debug,Clone)]pub enum E{Prt,Net(i32),Dsk(String),Acc,Get,Put,Cls}
#[derive(Debug)]pub struct G{pub n:Vec<N>,pub m:HashMap<String,usize>}
impl G{pub fn new()->Self{G{n:Vec::new(),m:HashMap::new()}}pub fn add(&mut self,node:N){if let Some(i)=Self::id(&node){self.m.insert(i,self.n.len());}self.n.push(node);}fn id(n:&N)->Option<String>{match n{N::L{i,..}|N::R{i,..}|N::O{i,..}|N::S{i,..}|N::F{i,..}=>Some(i.clone()),_=>None}}}
#[derive(Debug,Default)]pub struct U{pub ops:HashSet<O>,pub gui:bool,pub net:bool,pub thr:bool,pub fio:bool,pub con:bool}
impl U{pub fn analyze(g:&G)->Self{let mut u=U::default();for n in&g.n{u.visit(n);}u}fn visit(&mut self,n:&N){match n{N::O{o,..}=>{self.ops.insert(o.clone());self.cat(o);}N::F{b,..}=>{for x in b{self.visit(x);}}N::W{s,..}=>{if let A::E(o,_)=s{self.ops.insert(o.clone());self.cat(o);}}_=>{}}}fn cat(&mut self,o:&O){match o{O::Tcp|O::Udp|O::Bnd|O::Lst|O::Acc|O::Con|O::Xmt|O::Rcv|O::Sel|O::Rdy|O::Nbk|O::Ndl|O::Qck|O::Sbf|O::Kal|O::Epl|O::Ewa|O::Ect=>{self.net=true;}O::Thr|O::Jon|O::Mtx|O::Lck|O::Ulk|O::Que|O::Psh|O::Pop=>{self.thr=true;}O::Win|O::Shw|O::Hid|O::Evt|O::Run|O::Lbl|O::Txb|O::Btn|O::Dlg|O::Gvl|O::Svl=>{self.gui=true;}O::Opn|O::Get|O::Put|O::Cls=>{self.fio=true;}O::Prt|O::Inp|O::Err=>{self.con=true;}_=>{}}}}
pub fn parse(c:&str)->Result<G,String>{let mut g=G::new();let ls:Vec<&str>=c.lines().collect();let mut i=0;let mut cf:Option<(String,Vec<String>,Vec<N>)>=None;while i<ls.len(){let l=ls[i].trim();if l.is_empty()||l.starts_with("--"){i+=1;continue;}if l=="!"{i+=1;continue;}if l=="!FUN"{if let Some((id,p,b))=cf.take(){g.add(N::F{i:id,p,b});}i+=1;continue;}match pline(l){Ok(Some(n))=>{if let N::F{i:id,p,..}=&n{cf=Some((id.clone(),p.clone(),Vec::new()));}else if let Some((_,_,ref mut b))=cf{b.push(n);}else{g.add(n);}}Ok(None)=>{}Err(e)=>return Err(format!("L{}:{}",i+1,e))}i+=1;}Ok(g)}
fn pline(l:&str)->Result<Option<N>,String>{let l=scom(l);if l.contains(" > ")||l.contains(" >> "){return pflow(l);}if l.starts_with('.')&&l.contains(':'){return pdef(l);}if l.starts_with(':'){return Ok(Some(N::B(l[1..].trim().to_string())));}Err(format!("?:{}",l))}
fn scom(l:&str)->&str{let mut q=false;let c:Vec<char>=l.chars().collect();for i in 0..c.len(){if c[i]=='"'{q=!q;}else if!q&&i+1<c.len()&&c[i]=='-'&&c[i+1]=='-'{return l[..i].trim();}}l.trim()}
fn pdef(l:&str)->Result<Option<N>,String>{let p=l.find(':').ok_or("no:")?;let i=l[1..p].trim().to_string();let r=l[p+1..].trim();if r.starts_with("FUN"){let ps:Vec<String>=if r.len()>4{r[4..].split_whitespace().filter(|s|s.starts_with('.')).map(|s|s[1..].to_string()).collect()}else{vec![]};return Ok(Some(N::F{i,p:ps,b:vec![]}));}if r.starts_with('.')&&!r.contains(' '){return Ok(Some(N::R{i,t:r[1..].to_string()}));}if let Ok(v)=plit(r){return Ok(Some(N::L{i,v}));}pop(&i,r)}
fn plit(s:&str)->Result<V,String>{let s=s.trim();if s.starts_with('"')&&s.ends_with('"'){return Ok(V::S(s[1..s.len()-1].replace("\\n","\n").replace("\\r","\r").replace("\\t","\t").replace("\\0","\0").replace("\\\"","\"")));}if s.contains('.')&&!s.starts_with('.'){if let Ok(f)=s.parse::<f64>(){return Ok(V::F(f));}}if let Ok(n)=s.parse::<i64>(){return Ok(V::I(n));}Err(format!("?lit:{}",s))}
fn pop(i:&str,r:&str)->Result<Option<N>,String>{let t=tok(r);if t.is_empty(){return Err("empty".into());}let o=poop(&t[0])?;let a=pargs(&t[1..])?;Ok(Some(N::O{i:i.to_string(),o,a}))}
fn poop(s:&str)->Result<O,String>{match s.to_uppercase().as_str(){"ADD"=>Ok(O::Add),"SUB"=>Ok(O::Sub),"MUL"=>Ok(O::Mul),"DIV"=>Ok(O::Div),"MOD"=>Ok(O::Mod),"NEG"=>Ok(O::Neg),"EQ"=>Ok(O::Eq),"NE"=>Ok(O::Ne),"LT"=>Ok(O::Lt),"GT"=>Ok(O::Gt),"LE"=>Ok(O::Le),"GE"=>Ok(O::Ge),"AND"=>Ok(O::And),"OR"=>Ok(O::Or),"NOT"=>Ok(O::Not),"SEQ"=>Ok(O::Seq),"MAP"=>Ok(O::Map),"FLD"=>Ok(O::Fld),"FLT"=>Ok(O::Flt),"LEN"=>Ok(O::Len),"FST"=>Ok(O::Fst),"SND"=>Ok(O::Snd),"BRN"=>Ok(O::Brn),"PRT"=>Ok(O::Prt),"INP"=>Ok(O::Inp),"OPN"=>Ok(O::Opn),"ACC"=>Ok(O::Acc),"GET"=>Ok(O::Get),"PUT"=>Ok(O::Put),"CLS"=>Ok(O::Cls),"ERR"=>Ok(O::Err),"TCP"=>Ok(O::Tcp),"UDP"=>Ok(O::Udp),"BND"=>Ok(O::Bnd),"LST"=>Ok(O::Lst),"CON"=>Ok(O::Con),"XMT"=>Ok(O::Xmt),"RCV"=>Ok(O::Rcv),"ALC"=>Ok(O::Alc),"FRE"=>Ok(O::Fre),"CHK"=>Ok(O::Chk),"SEL"=>Ok(O::Sel),"RDY"=>Ok(O::Rdy),"NBK"=>Ok(O::Nbk),"NDL"=>Ok(O::Ndl),"QCK"=>Ok(O::Qck),"SBF"=>Ok(O::Sbf),"KAL"=>Ok(O::Kal),"EPL"=>Ok(O::Epl),"EWA"=>Ok(O::Ewa),"ECT"=>Ok(O::Ect),"THR"=>Ok(O::Thr),"JON"=>Ok(O::Jon),"MTX"=>Ok(O::Mtx),"LCK"=>Ok(O::Lck),"ULK"=>Ok(O::Ulk),"QUE"=>Ok(O::Que),"PSH"=>Ok(O::Psh),"POP"=>Ok(O::Pop),"RET"=>Ok(O::Ret),"WIN"=>Ok(O::Win),"SHW"=>Ok(O::Shw),"HID"=>Ok(O::Hid),"EVT"=>Ok(O::Evt),"RUN"=>Ok(O::Run),"LBL"=>Ok(O::Lbl),"TXB"=>Ok(O::Txb),"BTN"=>Ok(O::Btn),"DLG"=>Ok(O::Dlg),"GVL"=>Ok(O::Gvl),"SVL"=>Ok(O::Svl),s if s.starts_with('.')=>Ok(O::Cal(s[1..].to_string())),_=>Err(format!("?op:{}",s))}}
fn pargs(t:&[String])->Result<Vec<A>,String>{let mut a=Vec::new();let mut i=0;while i<t.len(){let x=&t[i];if x.starts_with('.'){a.push(A::R(x[1..].to_string()));i+=1;continue;}if x=="("{let(e,c)=pgrp(&t[i..])?;a.push(e);i+=c;continue;}if let Ok(v)=plit(x){a.push(A::L(v));i+=1;continue;}if x.starts_with('"'){let mut s=x.clone();while!s.ends_with('"')&&i+1<t.len(){i+=1;s.push(' ');s.push_str(&t[i]);}if let Ok(v)=plit(&s){a.push(A::L(v));i+=1;continue;}}return Err(format!("?arg:{}",x));}Ok(a)}
fn pgrp(t:&[String])->Result<(A,usize),String>{if t.is_empty()||t[0]!="("{return Err("no(".into());}let mut d=1;let mut e=1;while e<t.len()&&d>0{if t[e]=="("{d+=1;}else if t[e]==")"{d-=1;}if d>0{e+=1;}}if d!=0{return Err("unmatched(".into());}let inner=&t[1..e];if inner.is_empty(){return Err("empty()".into());}let o=poop(&inner[0])?;let a=pargs(&inner[1..].to_vec())?;Ok((A::E(o,a),e+1))}
fn pflow(l:&str)->Result<Option<N>,String>{let cy=l.contains(" >> ");let sep=if cy{" >> "}else{" > "};let p:Vec<&str>=l.split(sep).collect();if p.len()<2{return Err("bad>".into());}let s=psrc(p[0].trim())?;let d=pdst(p[1..].join(sep).trim(),cy)?;Ok(Some(N::W{s,d}))}
fn psrc(s:&str)->Result<A,String>{let s=s.trim();if s.starts_with('.'){return Ok(A::R(s[1..].to_string()));}if let Ok(v)=plit(s){return Ok(A::L(v));}let t=tok(s);if!t.is_empty(){let o=poop(&t[0])?;let a=pargs(&t[1..])?;return Ok(A::E(o,a));}Err(format!("?src:{}",s))}
fn pdst(s:&str,cy:bool)->Result<D,String>{let s=s.trim();match s.to_uppercase().as_str(){"PRT"=>return Ok(D::E(E::Prt)),_=>{}}if s.starts_with('.'){return Ok(if cy{D::C(s[1..].to_string())}else{D::N(s[1..].to_string())});}Err(format!("?dst:{}",s))}
fn tok(s:&str)->Vec<String>{let mut t=Vec::new();let mut c=String::new();let mut q=false;for x in s.chars(){if x=='"'{q=!q;c.push(x);}else if q{c.push(x);}else if x=='('||x==')'{if!c.is_empty(){t.push(c.clone());c.clear();}t.push(x.to_string());}else if x.is_whitespace(){if!c.is_empty(){t.push(c.clone());c.clear();}}else{c.push(x);}}if!c.is_empty(){t.push(c);}t}
